import { ClientType, PaymentType, UserRole, type Purchase } from './backend/models';

export const TEST_PURCHASES: Purchase[] = [
    {
        id: 'LTzpTK',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-20T22:31'),
        creator: {
            name: 'Яковлев Роман Эдуардович',
            id: 'f67d6s',
            role: UserRole.MANAGER,
            area: 'РТ',
        },
        supplier: 'Дубьязы',
        volumeInLiters: 1800,
        pricePerLiter: 10,
        area: 'РТ',
        invoiceINN: null,
        invoiceAccount: '0000',
        approved: true,
        approvedAt: new Date('2023-05-20T22:31'),
        approver: {
            name: 'Владелец',
            id: '777',
            role: UserRole.ADMIN,
            area: 'Universe',
        },
        totalPrice: 18000,
    },
    {
        id: 'V6bUPQ',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-20T22:29'),
        creator: {
            name: 'Яковлев Роман Эдуардович',
            id: 'f67d6s',
            role: UserRole.MANAGER,
            area: 'РТ',
        },
        supplier: 'Братьев Касимовых',
        volumeInLiters: 300,
        pricePerLiter: 10,
        area: 'РТ',
        invoiceINN: null,
        invoiceAccount: '0000',
        approved: true,
        approvedAt: new Date('2023-05-20T22:31'),
        approver: {
            name: 'Владелец',
            id: '777',
            role: UserRole.ADMIN,
            area: 'Universe',
        },
        totalPrice: 3000,
    },
    {
        id: 'PdfeYl',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-20T22:17'),
        creator: {
            name: 'Владелец',
            id: '777',
            role: UserRole.ADMIN,
            area: 'Universe',
        },
        supplier: 'Оклада',
        volumeInLiters: 1704.545455,
        pricePerLiter: 13.63636364,
        area: '123123',
        invoiceINN: null,
        invoiceAccount: '-',
        approved: true,
        approvedAt: new Date('2023-06-17T17:30'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 23200,
    },
    {
        id: 'sSoxIq',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-20T16:39'),
        creator: {
            name: 'Кривозубов Андрей Сергеевич',
            role: UserRole.EMPLOYEE,
            id: 'af96sf',
            area: 'РК+ЮФО',
        },
        supplier: 'Андрей',
        volumeInLiters: 550,
        pricePerLiter: 10,
        area: '+79789601340',
        invoiceINN: 'РК+ЮФО',
        invoiceAccount: '20.05.2023 16:47',
        approved: true,
        approvedAt: new Date('2023-05-20T16:47'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 5500,
    },
    {
        id: 'um2zZB',
        paymentType: PaymentType.CASH,
        clientType: ClientType.MANAGED,
        createdAt: new Date('2023-05-20T15:05'),
        creator: {
            name: 'Кривозубов Андрей Сергеевич',
            role: UserRole.EMPLOYEE,
            id: 'af96sf',
            area: 'РК+ЮФО',
        },
        supplier: 'Елена',
        volumeInLiters: 900,
        pricePerLiter: 11,
        area: '+79785067737',
        invoiceINN: 'РК+ЮФО',
        invoiceAccount: '20.05.2023 16:49',
        approved: true,
        approvedAt: new Date('2023-05-20T16:49'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 9900,
    },
    {
        id: 'CPQNVD',
        paymentType: PaymentType.CARD,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-20T13:00'),
        creator: {
            name: 'Кривозубов Андрей Сергеевич',
            role: UserRole.EMPLOYEE,
            id: 'af96sf',
            area: 'РК+ЮФО',
        },
        supplier: 'Кфк таврида',
        volumeInLiters: 1900,
        pricePerLiter: 12,
        area: 'WTF',
        invoiceINN: 'РК+ЮФО',
        invoiceAccount: '20.05.2023 13:04',
        approved: true,
        approvedAt: new Date('2023-05-20T13:04'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 22800,
    },
    {
        id: 'Yyvcpx',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-19T15:20'),
        creator: {
            name: 'Кривозубов Андрей Сергеевич',
            role: UserRole.EMPLOYEE,
            id: 'af96sf',
            area: 'РК+ЮФО',
        },
        supplier: 'Андрей',
        volumeInLiters: 1800,
        pricePerLiter: 15,
        area: '+79788083445',
        invoiceINN: 'РК+ЮФО',
        invoiceAccount: '19.05.2023 15:45',
        approved: true,
        approvedAt: new Date('2023-05-19T15:45'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 27000,
    },
    {
        id: 'NF22NK',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-19T12:27'),
        creator: {
            name: 'Новиков Артём Андреевич',
            area: 'РК+ЮФО',
            id: 'asdsad',
            role: UserRole.MANAGER,
        },
        supplier: 'Сто',
        volumeInLiters: 630,
        pricePerLiter: 10,
        area: '89271396069',
        invoiceINN: 'Саратов',
        invoiceAccount: '19.05.2023 12:38',
        approved: true,
        approvedAt: new Date('2023-05-19T12:38'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 6300,
    },
    {
        id: 'eR5w8D',
        paymentType: PaymentType.CASH,
        clientType: ClientType.PERSONAL,
        createdAt: new Date('2023-05-19T10:12'),
        creator: {
            name: 'Новиков Артём Андреевич',
            area: 'РК+ЮФО',
            id: 'asdsad',
            role: UserRole.MANAGER,
        },
        supplier: 'Сто',
        volumeInLiters: 1000,
        pricePerLiter: 10,
        area: '8 (902) 040-81-81',
        invoiceINN: 'Саратов',
        invoiceAccount: '19.05.2023 12:38',
        approved: true,
        approvedAt: new Date('2023-05-19T12:38'),
        approver: {
            name: 'Смаль Александр Викторович',
            role: UserRole.EMPLOYEE,
            id: 'asdsad',
            area: 'РК+ЮФО',
        },
        totalPrice: 10000,
    },
];
